// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXlgHN7vYdcQyVZcb0DIzVrSwm5DQYN24',
    appId: '1:744132228349:web:699f0938d5f1c6b9077a94',
    messagingSenderId: '744132228349',
    projectId: 'expensetracker-36907',
    authDomain: 'expensetracker-36907.firebaseapp.com',
    storageBucket: 'expensetracker-36907.firebasestorage.app',
    measurementId: 'G-QP9SK7SZ79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCezKfBAXx-YE4hChVfyciIcnftfFQYMx8',
    appId: '1:744132228349:android:80cdfba959ac9f9b077a94',
    messagingSenderId: '744132228349',
    projectId: 'expensetracker-36907',
    storageBucket: 'expensetracker-36907.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXlgHN7vYdcQyVZcb0DIzVrSwm5DQYN24',
    appId: '1:744132228349:web:acd599e7b46002bc077a94',
    messagingSenderId: '744132228349',
    projectId: 'expensetracker-36907',
    authDomain: 'expensetracker-36907.firebaseapp.com',
    storageBucket: 'expensetracker-36907.firebasestorage.app',
    measurementId: 'G-WGEKC9M9PX',
  );

}